// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rviwdobaeyhnwzkinefj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2aXdkb2JhZXlobnd6a2luZWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzU2MjUsImV4cCI6MjA2NjYxMTYyNX0.Q8ftNrkzgnDrjxVy4wrYwzTyAM_7B4dKtcDfPB7N4dU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);